spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: root
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.liang.lxspringbootmybatismapper.Dao
  #注解模式不需要搜索mapper地址
  mapper-locations: classpath:mapper/*.xml